#!/usr/bin/env bash
# SessionStart: one-line nudge to run /first-run when the project profile is
# missing OR was generated by an older plugin version (stale schema).
# The whole plugin specializes to .claude/essentials-profile.md — this is the
# only place a user learns that if they haven't read the README.
# Silence with ESSENTIALS_NO_NUDGE=1. Always exits 0.

set -u
cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0
[ -d .git ] || exit 0
[ -n "${ESSENTIALS_NO_NUDGE:-}" ] && exit 0

# Must match the marker /first-run writes into the profile header.
# Bump both together when the profile template gains or renames fields.
SCHEMA="profile-schema: 2"

if [ -f .claude/essentials-profile.md ]; then
  grep -q "$SCHEMA" .claude/essentials-profile.md && exit 0
  echo "essentials: the project profile predates this plugin version. Suggest re-running /first-run to pick up the new profile fields — it updates in place and keeps hand edits. (Silence this nudge with ESSENTIALS_NO_NUDGE=1.)"
  exit 0
fi

echo "essentials: no project profile found. Suggest running /first-run once — it detects this repo's stack/commands/layout and tailors every essentials agent to it. (Silence this nudge with ESSENTIALS_NO_NUDGE=1.)"
exit 0
